# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
install!'cocoapods',:deterministic_uuids=>false
use_frameworks!
inhibit_all_warnings!

pre_install do |installer|
  
    installer.pod_targets.each do |target|
        target.specs.each do |spec|
            spec.static_framework = true
            spec.root.static_framework = true
        end
    end
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
#    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'RTEVideoEditor' do
  use_frameworks!
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for RTEVideoEditor
  pod 'FFmpeg-Pod', :path => './FFmpeg-Pod', :inhibit_warnings => true
  pod 'SnapKit'

end
